from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class WorkStatus(str, Enum):
    COMPLETED = "Completed"
    IN_PROGRESS = "In Progress"
    SANCTIONED = "Sanctioned"
    STALLED = "Stalled"

class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class Finding(BaseModel):
    title: str
    description: str
    evidence: List[str]
    confidence: float = Field(..., ge=0.0, le=1.0)
    severity: Severity = Severity.MEDIUM
    metric: Optional[str] = None
    observed_value: Optional[Any] = None
    expected_value: Optional[Any] = None

class AgentResponse(BaseModel):
    agent: str
    risk_level: RiskLevel
    score: float = Field(..., ge=0.0, le=100.0)
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    findings: List[Finding] = []

class DataQualityFlag(BaseModel):
    field: str
    issue_type: str
    severity: Severity
    message: str
    value: Optional[Any] = None

class PeerStats(BaseModel):
    peer_group_name: str
    peer_count: int
    median_cost: float
    mean_cost: float
    p25_cost: float
    p75_cost: float
    p90_cost: float
    median_duration: Optional[float] = None
    cost_deviation_pct: float
    cost_z_score: float
    cost_percentile: float

class EvidencePackage(BaseModel):
    work_id: str
    financial_findings: List[Finding] = []
    progress_findings: List[Finding] = []
    geographic_findings: List[Finding] = []
    anomaly_findings: List[Finding] = []
    data_quality_flags: List[DataQualityFlag] = []
    peer_stats: Optional[PeerStats] = None

class LeadInvestigatorReport(BaseModel):
    work_id: str
    overall_risk: RiskLevel
    risk_score: float = Field(..., ge=0.0, le=100.0)
    confidence: float = Field(..., ge=0.0, le=100.0)
    executive_summary: str
    key_findings: List[str]
    corroborating_evidence: List[str]
    contradictory_evidence: List[str]
    geographic_analysis: str
    recommendation: str
    requires_physical_verification: bool
    evidence_summary: Dict[str, str]
    disclaimer: str = (
        "IMPORTANT DISCLAIMER: This report is a decision-support and audit-prioritization aid generated by "
        "TransTrack 2 for MPLADS monitoring. It identifies statistical anomalies, financial patterns, and progress variances based "
        "on available data. It does NOT declare or establish fraud, corruption, or legal wrongdoing. All findings "
        "must be corroborated through standard administrative review and on-site physical inspection."
    )

class WorkBase(BaseModel):
    work_id: str
    mp_name: str
    mp_house: str = "Lok Sabha"
    constituency: str
    state: str
    district: str
    block: Optional[str] = None
    village: Optional[str] = None
    implementing_agency: str
    work_type: str
    work_description: str
    sanctioned_amount: float
    released_amount: float
    expenditure: float
    balance_amount: float
    work_status: str
    recommendation_date: Optional[str] = None
    sanction_date: Optional[str] = None
    completion_date: Optional[str] = None
    financial_year: str
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    is_demo: bool = True

class WorkCreate(WorkBase):
    pass

class WorkRead(WorkBase):
    id: int
    risk_score: Optional[float] = 0.0
    risk_level: Optional[str] = "LOW"
    top_finding: Optional[str] = None
    utilization_percentage: Optional[float] = 0.0

    class Config:
        from_attributes = True

class WorkInvestigationResult(BaseModel):
    work: WorkRead
    evidence_package: EvidencePackage
    agent_responses: Dict[str, AgentResponse]
    report: LeadInvestigatorReport
    why_flagged: List[str]
    peer_comparison: Optional[PeerStats] = None

class DashboardSummary(BaseModel):
    total_works: int
    total_sanctioned: float
    total_expenditure: float
    overall_utilization: float
    completed_works: int
    in_progress_works: int
    sanctioned_works: int
    stalled_works: int
    critical_risk_count: int
    high_risk_count: int
    medium_risk_count: int
    low_risk_count: int
    risk_distribution: List[Dict[str, Any]]
    status_distribution: List[Dict[str, Any]]
    district_summary: List[Dict[str, Any]]
    work_type_summary: List[Dict[str, Any]]

class WeightConfig(BaseModel):
    weight_financial: float = 0.30
    weight_progress: float = 0.25
    weight_anomaly: float = 0.25
    weight_geographic: float = 0.20
    threshold_low: float = 30.0
    threshold_medium: float = 60.0
    threshold_high: float = 80.0
